### ISSUE TITLE
Question about F1 results

### ISSUE THREAD

**Issue by heslowen** [monologg/R-BERT#1]
Hello, thanks for your works. 
I got the final F1 result 82.0% after 5 epoch training while 89.25% in the paper. What about you?

**Comment by monologg** [comment]
Hi:) As I write on the READMEpage, the score shown during training is " NOT OFFICIAL SCORE of SemEval 2010 Task 8".  Actually there is a Official perl script for testing. I made a wrapper python file (official_eval.py). You may run this one:) Acually in my case, 88.92% is the max f1 score that I got.

**Comment by monologg** [comment]
If your 82% is come from official score, I recommend you to change the random seed and try it again

**Comment by heslowen** [comment]
aha, thank you so much! @monologg

**Comment by xxl95** [comment]
Traceback (most recent call last):
  File "D:/WorkSpace/Pythonspace/R-BERT-master/official_eval.py", line 24, in <module>
    print("macro-averaged F1 = {}%".format(official_f1() * 100))
  File "D:/WorkSpace/Pythonspace/R-BERT-master/official_eval.py", line 15, in official_f1
    macro_result = list(f)[-1]
IndexError: list index out of range

When I run the official_eval.py file, I keep reporting this error. I don’t understand perl, can you give me some advice?
