### ISSUE TITLE
How can i train my own dataset?

### ISSUE THREAD

**Issue by FengLizheng** [monologg/R-BERT#2]

**Comment by monologg** [comment]
1. Define your classes in `label.txt` in `data` directory
2. Make your data's formats as same as `train.tsv`.
- Embracing entities with <e1> </e1> <e2> </e2>

**Comment by FengLizheng** [comment]
OK,Thank you so much Park.
So , I can just train the model by input
"python main.py --do_train" command?
and the trained model will be saved when finish the train process?

**Comment by monologg** [comment]
> OK,Thank you so much Park.
> So , I can just train the model by input
> "python main.py --do_train" command?
> and the trained model will be saved when finish the train process?

Yes It does. You may try with your own dataset

**Comment by FengLizheng** [comment]
> > OK,Thank you so much Park.
> > So , I can just train the model by input
> > "python main.py --do_train" command?
> > and the trained model will be saved when finish the train process?
> 
> Yes It does. You may try with your own dataset

It's so nice of you .
