### ISSUE TITLE
How can I retrain the model from the past trained model ?

### ISSUE THREAD

**Issue by FengLizheng** [monologg/R-BERT#4]
As above
Thanks Park.

**Comment by monologg** [comment]
I didn't implement that one on this code. You should save `optimizer` and `scheduler` and load those two stuff when retraining.

Please check the link below:)
https://github.com/huggingface/transformers/blob/d13eca11e2/examples/run_glue.py#L246-L248
https://github.com/huggingface/transformers/blob/d13eca11e2/examples/run_glue.py#L104-L109

**Comment by monologg** [comment]
Closing, feel free to reopen if I haven't fully answered your questions.
