### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by RingoTC** [monologg/R-BERT#6]
07/01/2020 19:31:38 - INFO - data_loader -   Loading features from cached file ./data/cached_train_semeval_bert-base-uncased_384
Segmentation fault (core dumped)

I run this model without any changes.

**Comment by monologg** [comment]
@RingoTC 

I've never seen this issue before. It looks like "out of memory" issue. Can you tell me how much memory you have for cpu and gpu?
